= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v1.2.0...v1.2.1++[1.2.1^] (2020-12-16)

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/8e26a96cb00ebc829c8162b9c3b02e9c254bd7da[8e26a96^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/8e7cc2e52c5e759534bff786280948e770fab63f[8e7cc2e^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/cc0d0c3f46834f625e987c38d167a4661d057714[cc0d0c3^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/ded370b94903a7c9a6c8ad41ac339d3e3e34b458[ded370b^])

=== Documentation

* *readme:* fix `rstcheck` violation [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/e89a3341d00b45d2277ad18ecb3d09a69cf04f49[e89a334^]),
closes
https://github.com//travis-ci.org/github/myii/jetbrains-rider-formula/builds/731607162/issues/L259[/travis-ci.org/github/myii/jetbrains-rider-formula/builds/731607162#L259^]

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v1.1.0...v1.2.0++[1.2.0^] (2020-09-20)

=== Features

* *clean:* add windows support
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/acd6eaf925ebf475a064b77f1c2286a563cdd29f[acd6eaf^])
* *windows:* basic windows support
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/a44ca281592dee8a1eb254b705af424f38907061[a44ca28^])

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v1.0.2...v1.1.0++[1.1.0^] (2020-09-20)

=== Features

* *windows:* basic windows support
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/0c4e6ce89daf8f908cd330955d2e88c6b0888473[0c4e6ce^])

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2020-07-28)

=== Bug Fixes

* *cmd.run:* wrap url in quotes (zsh)
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/cfb5bba642f978cb27d5970651421626587f6387[cfb5bba^])
* *macos:* correct syntax
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/e6e8ceab64026d3d31f651f5408ab319b5c9a31f[e6e8cea^])
* *macos:* do not create shortcut file
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/5f2228e530d0c483dd3339cf332f15da79fc69a5[5f2228e^])
* *macos:* do not create shortcut file
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/42a7b889dda10f9cabdae81e01cb2fad411c608d[42a7b88^])
* *macos:* do not create shortcut file
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/b07e7badf3013620a864f9166c5bf449825e7cb2[b07e7ba^])

=== Code Refactoring

* *jetbrains:* align jetbrains formulas
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/00c79672fedae7eeb2dc0ed2c8b35121dc78e584[00c7967^])
* *path:* consistent path vars
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/7a53c74486c8f27f971202783c40491f6ebc41a3[7a53c74^])

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/f3c358f7b075fe9c3a2ed7a9cbd43422f3e1fd46[f3c358f^])

=== Documentation

* *readme:* minor update
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/e448d069771c7e9b67dbd04ab080630c6356e2d3[e448d06^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/ef0024db97eacf3840102498f2573403ea690834[ef0024d^])

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2020-06-15)

=== Bug Fixes

* *edition:* better edition jinja code
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/ef934370c91bd4ba7bd48f7a458f50ba524062a9[ef93437^])

=== Continuous Integration

* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/9ea7137aa076b6739cc0c672ad95d2f18b977e88[9ea7137^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/89c56b855fba5836a93af941cf1418fc128cd55f[89c56b8^])

=== Documentation

* *readme:* updated formatting
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/0af6a346afc9cbad6d21f35f92a58c9d83c2bce4[0af6a34^])

== link:++https://github.com/saltstack-formulas/jetbrains-rider-formula/compare/v0.2.0...v1.0.0++[1.0.0^] (2020-05-18)

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000.3`
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/26c3122ed7176c72ea3a9efa7b1d81c69215ba41[26c3122^])

=== Documentation

* *readme:* add depth one
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/e0ce7f6b3572f93d85ab53c4b79303c3b74f6ac5[e0ce7f6^])

=== Features

* *formula:* align to template-formula; add ci
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/ca4a346364c6583cb5bb1ea958073bdfff44a125[ca4a346^])
* *formula:* align to template-formula; add ci
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/d24b3111f76543a76412eefa828212bc019c73b0[d24b311^])
* *semantic-release:* standardise for this formula
(https://github.com/saltstack-formulas/jetbrains-rider-formula/commit/a666df821e1e6a7d4fc78c16641ce6a7d7f2ea37[a666df8^])

=== BREAKING CHANGES

* *formula:* Major refactor of formula to bring it in alignment with the
template-formula. As with all substantial changes, please ensure your
existing configurations work in the ways you expect from this formula.
